server:
  port: 8888

spring:
  application:
    name: my-config-server
  profiles:
    active: native
  # 指定配置文件的位置，不指定则默认去[classpath:/, classpath:/config, file:./, file:./config]这些目录找
  # 注意：只能除了classpath外只能配置绝对路径
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#          search-locations: file:C:/config
