nickname: Local

feign:
  hystrix:
    enabled: true

#hystrix:
#  ribbon:
#    ConnectTimeout: 60000
#    ReadTimeout: 60000
#  threadpool:
#    default:
#      coreSize: 10
#  command:
#    default:
#      circuitBreaker:
#        enabled: true
#      execution:
#        isolation:
#          thread:
#            # 线程超时时间（默认1000毫秒）
#            timeoutInMilliseconds: 300